# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53360c38bce13caf07441c5a7521c1b641f7000a952c93b96c12b12db6e5fae94aba59071c8fc14771353eff6b6ff3f8e063dc27cb718b808dff0afe9776945a

test:
  secret_key_base: 1c6899b7be927f5730ea5e53730d323c3c3a8ac4336b2ed29a1b0623f8066c7ebda8b50e9b441c2b91e0bd636d1fe7bc3b646edbd00fb481ad2709f56f94b17a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
